--- pyproject.toml.orig	2026-04-03 09:42:49 UTC
+++ pyproject.toml
@@ -3,8 +3,7 @@ description = "libcurl ffi bindings for Python, with i
 version = "0.15.0"
 authors = [{ name = "lexiforest", email = "infinitesheldon@gmail.com" }]
 description = "libcurl ffi bindings for Python, with impersonation support."
-license = "MIT"
-license-files = ["LICENSE"]
+license = { text = "MIT" }
 dependencies = [
     "cffi>=2.0.0",
     "certifi>=2024.2.2",
